/**
 * ApexYY (云翼) Node Configuration
 * Auto-generated by ClawX OEM Generator
 */

export interface OEMNode {
  id: number;
  name: string;
  nameZh: string;
  baseUrl: string;
  region: "domestic" | "overseas" | "backup";
}

export const APEXYY_NODES: OEMNode[] = [
  { id: 1, name: "China Main", nameZh: "国内主节点", baseUrl: "https://yunyi.rdzhvip.com", region: "domestic" },
  { id: 2, name: "CF Overseas 1", nameZh: "CF国外节点1", baseUrl: "https://yunyi.cfd", region: "overseas" },
  { id: 3, name: "CF Overseas 2", nameZh: "CF国外节点2", baseUrl: "https://cdn1.yunyi.cfd", region: "overseas" },
  { id: 4, name: "CF Overseas 3", nameZh: "CF国外节点3", baseUrl: "https://cdn2.yunyi.cfd", region: "overseas" },
  { id: 5, name: "Backup 1", nameZh: "备用节点1", baseUrl: "http://47.99.42.193", region: "backup" },
  { id: 6, name: "Backup 2", nameZh: "备用节点2", baseUrl: "http://47.97.100.10", region: "backup" },
];

export const DEFAULT_NODE = APEXYY_NODES[0];

export function getClaudeBaseUrl(node: OEMNode): string {
  return `${node.baseUrl}/claude`;
}

export function getCodexBaseUrl(node: OEMNode): string {
  return `${node.baseUrl}/codex`;
}
